### ISSUE TITLE
"This version of Blender does not support 'Display GPU'" error

### ISSUE THREAD

**Issue by Lamea132** [abrasic/blendpresence#15]
So Blender Presence was working for a while and for some reason when I opened up Blender, it doesn't take me to the splash screen and instead the console for Blender is stuck where this line is: ![image](https://github.com/abrasic/blendpresence/assets/76811768/7568a1a7-82d7-4e44-a4a1-82a58585a4e2)
I updated my Blender and the same thing happens on the 3.6 version also and taking the addon off makes Blender start up as normal. I was wondering how I can fix this problem.

**Comment by abrasic** [comment]
Hello,
I've been able to reproduce the console error in Bforartists 3.6 but am still able to use the application as normal despite the error. Are you also able to see a `[BP] Connected!` print right below it? Or does it just stop there?

Another thing to keep in mind that if you click inside the console window, this freezes blender until you hit the `Enter` key. You can determine if your console is in this state if it has the text `Select` in the window title, like this:
![image](https://github.com/abrasic/blendpresence/assets/43157991/4bb36b05-a940-4d49-8037-4e00f8267fd2)

**Comment by Lamea132** [comment]
I never received the "[BP] Connected!" line. I made sure that I selected the console like I'm supposed to.

**Comment by abrasic** [comment]
I also realized I forgot to include Blender 4.0 in a specific statement to send the proper command for Displaying the GPU name.

Could you try this potential solution to see if this fixes anything?
- Close blender.
- Go to line 39 of `*your_blender_install_folder*\scripts\addons\blendpresence\__init__.py`
- Change this:
```elif bpy.app.version[0] == 3 and bpy.app.version[1] >= 0:```
To this:
```elif bpy.app.version[0] >= 3 and bpy.app.version[1] >= 0:```
- Save the file and restart blender

The solution above also fixes my issue with Display GPU not working on Blender 4.0.

If the above solution does not work, it could be because the add-on is hanging due to not being able to connect to the RPC properly (one of the biggest issues with BP right now is that this addon will hang indefinitely until a proper connection is made). This could be caused due to networking/firewall issues or Discord preventing the connection somehow. It's probably obvious at this point but make sure that a Discord client is running whilst running BlendPresence

**Comment by Lamea132** [comment]
THANK YOU ONCE AGAIN! It worked!
